### PR TITLE
Not sure why the CI isn't uploading any more

### PR DESCRIPTION
**Pull request by dpryan79**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dpryan79** [comment]
@conda-forge-admin, please rerender

**Comment by dbast** [comment]
This correctly triggered all CIs.

**Comment by dbast** [comment]
Lets see if they also get triggered on master after merge.

**Comment by dpryan79** [comment]
Seems to have worked this time, thanks @dbast !

**Pull request merged**
